org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

archives_base_name=cobblemon-escape-rope
mod_id=cobblemon_escape_rope
mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Cobblemon Escape Rope
mod_description=A simple mod that adds an escape rope item to Cobblemon.
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/cobblemon-escape-rope/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/cobblemon-escape-rope
git_url=github.com/Matthiesen-dev/cobblemon-escape-rope
modrinth_url=https://modrinth.com/mod/cobblemon-escape-rope

# Used for prism deployment, not consumed by build-logic
minecraft_version=1.21.1

# To be removed
architectury_version=13.0.8